// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinancialManagement.Infrastructure.Persistence.Context;

#nullable disable

namespace PersonalFinancialManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalFinancialManagement.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("DeletedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DeletedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("PersonalFinancialManagement.Core.Entities.ToPay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CategoryId");

                    b.Property<Guid>("Transaction")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("TransactionId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("ToPay", (string)null);
                });

            modelBuilder.Entity("PersonalFinancialManagement.Core.Entities.ToReceive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("CategoryId");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("TransactionId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("ToReceive", (string)null);
                });

            modelBuilder.Entity("PersonalFinancialManagement.Core.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToPayId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ToPayId");

                    b.Property<Guid>("ToReceiveId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("ToReceiveId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("PersonalFinancialManagement.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("CreatedAt");

                    b.Property<byte[]>("DeletedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DeletedAt");

                    b.HasKey("Id");

                    b.ToTable("Transfers", (string)null);
                });

            modelBuilder.Entity("PersonalFinancialManagement.Core.Entities.Category", b =>
                {
                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.TransactionDate", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Date")
                                .IsRequired()
                                .HasColumnType("TIMESTAMP")
                                .HasColumnName("Created At");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Category");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.AdditionalInformation", "Description", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Information")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Description");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Category");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.AdditionalInformation", "Observation", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Information")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Observation");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Category");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("CreatedAt")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Observation")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinancialManagement.Core.Entities.ToPay", b =>
                {
                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.Amount", "AmountPaid", b1 =>
                        {
                            b1.Property<Guid>("ToPayId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(00,00)")
                                .HasColumnName("Amount Paid");

                            b1.HasKey("ToPayId");

                            b1.ToTable("ToPay");

                            b1.WithOwner()
                                .HasForeignKey("ToPayId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.TransactionDate", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("ToPayId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Date")
                                .IsRequired()
                                .HasColumnType("TIMESTAMP")
                                .HasColumnName("Created At");

                            b1.HasKey("ToPayId");

                            b1.ToTable("ToPay");

                            b1.WithOwner()
                                .HasForeignKey("ToPayId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.AdditionalInformation", "Description", b1 =>
                        {
                            b1.Property<Guid>("ToPayId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Information")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Description");

                            b1.HasKey("ToPayId");

                            b1.ToTable("ToPay");

                            b1.WithOwner()
                                .HasForeignKey("ToPayId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.TransactionDate", "DueDate", b1 =>
                        {
                            b1.Property<Guid>("ToPayId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Date")
                                .IsRequired()
                                .HasColumnType("TIMESTAMP")
                                .HasColumnName("Due Date");

                            b1.HasKey("ToPayId");

                            b1.ToTable("ToPay");

                            b1.WithOwner()
                                .HasForeignKey("ToPayId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.Amount", "OriginalValue", b1 =>
                        {
                            b1.Property<Guid>("ToPayId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(00,00)")
                                .HasColumnName("Original Value");

                            b1.HasKey("ToPayId");

                            b1.ToTable("ToPay");

                            b1.WithOwner()
                                .HasForeignKey("ToPayId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.TransactionDate", "PaymentDate", b1 =>
                        {
                            b1.Property<Guid>("ToPayId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Date")
                                .IsRequired()
                                .HasColumnType("TIMESTAMP")
                                .HasColumnName("Payment Date");

                            b1.HasKey("ToPayId");

                            b1.ToTable("ToPay");

                            b1.WithOwner()
                                .HasForeignKey("ToPayId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.TransactionDate", "ReferenceDate", b1 =>
                        {
                            b1.Property<Guid>("ToPayId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Date")
                                .IsRequired()
                                .HasColumnType("TIMESTAMP")
                                .HasColumnName("Reference Date");

                            b1.HasKey("ToPayId");

                            b1.ToTable("ToPay");

                            b1.WithOwner()
                                .HasForeignKey("ToPayId");
                        });

                    b.Navigation("AmountPaid")
                        .IsRequired();

                    b.Navigation("CreatedAt")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("DueDate")
                        .IsRequired();

                    b.Navigation("OriginalValue")
                        .IsRequired();

                    b.Navigation("PaymentDate")
                        .IsRequired();

                    b.Navigation("ReferenceDate")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinancialManagement.Core.Entities.ToReceive", b =>
                {
                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.Amount", "AmountReceived", b1 =>
                        {
                            b1.Property<Guid>("ToReceiveId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(00,00)")
                                .HasColumnName("Amount Received");

                            b1.HasKey("ToReceiveId");

                            b1.ToTable("ToReceive");

                            b1.WithOwner()
                                .HasForeignKey("ToReceiveId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.TransactionDate", "CreatedAt", b1 =>
                        {
                            b1.Property<Guid>("ToReceiveId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Date")
                                .IsRequired()
                                .HasColumnType("TIMESTAMP")
                                .HasColumnName("Created At");

                            b1.HasKey("ToReceiveId");

                            b1.ToTable("ToReceive");

                            b1.WithOwner()
                                .HasForeignKey("ToReceiveId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.TransactionDate", "DateReceipt", b1 =>
                        {
                            b1.Property<Guid>("ToReceiveId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Date")
                                .IsRequired()
                                .HasColumnType("TIMESTAMP")
                                .HasColumnName("Date Receipt");

                            b1.HasKey("ToReceiveId");

                            b1.ToTable("ToReceive");

                            b1.WithOwner()
                                .HasForeignKey("ToReceiveId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.AdditionalInformation", "Description", b1 =>
                        {
                            b1.Property<Guid>("ToReceiveId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Information")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Description");

                            b1.HasKey("ToReceiveId");

                            b1.ToTable("ToReceive");

                            b1.WithOwner()
                                .HasForeignKey("ToReceiveId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.TransactionDate", "DueDate", b1 =>
                        {
                            b1.Property<Guid>("ToReceiveId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Date")
                                .IsRequired()
                                .HasColumnType("TIMESTAMP")
                                .HasColumnName("Due Date");

                            b1.HasKey("ToReceiveId");

                            b1.ToTable("ToReceive");

                            b1.WithOwner()
                                .HasForeignKey("ToReceiveId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.AdditionalInformation", "Observation", b1 =>
                        {
                            b1.Property<Guid>("ToReceiveId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Information")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Observation");

                            b1.HasKey("ToReceiveId");

                            b1.ToTable("ToReceive");

                            b1.WithOwner()
                                .HasForeignKey("ToReceiveId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.Amount", "OriginalValue", b1 =>
                        {
                            b1.Property<Guid>("ToReceiveId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(00,00)")
                                .HasColumnName("Original Value");

                            b1.HasKey("ToReceiveId");

                            b1.ToTable("ToReceive");

                            b1.WithOwner()
                                .HasForeignKey("ToReceiveId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.TransactionDate", "ReferenceDate", b1 =>
                        {
                            b1.Property<Guid>("ToReceiveId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Date")
                                .IsRequired()
                                .HasColumnType("TIMESTAMP")
                                .HasColumnName("Reference Date");

                            b1.HasKey("ToReceiveId");

                            b1.ToTable("ToReceive");

                            b1.WithOwner()
                                .HasForeignKey("ToReceiveId");
                        });

                    b.Navigation("AmountReceived")
                        .IsRequired();

                    b.Navigation("CreatedAt")
                        .IsRequired();

                    b.Navigation("DateReceipt")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("DueDate")
                        .IsRequired();

                    b.Navigation("Observation")
                        .IsRequired();

                    b.Navigation("OriginalValue")
                        .IsRequired();

                    b.Navigation("ReferenceDate")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinancialManagement.Core.Entities.Transaction", b =>
                {
                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.Amount", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("DECIMAL(00,00)")
                                .HasColumnName("Amount");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.AdditionalInformation", "Description", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Information")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Description");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.TransactionDate", "TransactionDate", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<byte[]>("Date")
                                .IsRequired()
                                .HasColumnType("TIMESTAMP")
                                .HasColumnName("Transaction Date");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("PersonalFinancialManagement.Core.ValueObjects.TransactionType", "Modality", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Details")
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Details");

                            b1.Property<string>("Installments")
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Installments");

                            b1.Property<string>("Modality")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Modality");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transaction");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Modality")
                        .IsRequired();

                    b.Navigation("TransactionDate")
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinancialManagement.Core.Entities.User", b =>
                {
                    b.OwnsOne("DomainDesign.ValueObjects.Email", "EmailAddress", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Transfers");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("DomainDesign.ValueObjects.Name", "FullName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("IndividualsName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Name");

                            b1.HasKey("UserId");

                            b1.ToTable("Transfers");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("DomainDesign.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("VARCHAR")
                                .HasColumnName("Password");

                            b1.HasKey("UserId");

                            b1.ToTable("Transfers");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("EmailAddress")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
